<?php

namespace PSolutions\EncryptBundle\Encryptors;

use Exception;
use PSolutions\EncryptBundle\Event\EncryptKeyEvent;
use PSolutions\EncryptBundle\Event\EncryptKeyEvents;
use PSolutions\EncryptBundle\EventListener\DoctrineEncryptListenerInterface;
use PSolutions\EncryptBundle\Exception\EncryptException;
use Symfony\Component\EventDispatcher\EventDispatcherInterface;

/**
 * Class for OpenSSL encryption using AES-256-GCM (authenticated encryption).
 *
 * IMPORTANT: This implementation uses AES-256-GCM which provides both
 * confidentiality AND authenticity. Data encrypted with this class cannot
 * be tampered with without detection.
 *
 * @author Mark Ogilvie <mark.ogilvie@ogilvieconsulting.net>
 */
class OpenSslEncryptor implements EncryptorInterface
{
    /**
     * Cipher method: AES-256-GCM
     * Provides authenticated encryption (AEAD)
     */
    public const METHOD = 'aes-256-gcm';

    /**
     * Length of the authentication tag in bytes
     * 16 bytes = 128-bit tag (recommended for GCM)
     */
    private const TAG_LENGTH = 16;

    /**
     * Length of the initialization vector (IV) in bytes
     * 12 bytes = 96 bits (recommended for GCM performance)
     */
    private const IV_LENGTH = 12;

    /**
     * Secret key stored in .env and passed via parameters.
     * Must be 256-bit (32 bytes after base64_decode)
     */
    private string $secretKey;

    private EventDispatcherInterface $dispatcher;

    /**
     * OpenSslEncryptor constructor.
     */
    public function __construct(EventDispatcherInterface $dispatcher)
    {
        $this->dispatcher = $dispatcher;
    }

    public function __toString(): string
    {
        return self::class . ':' . self::METHOD;
    }

    /**
     * Set the secret encryption key.
     * The key will be validated (decoded and length-checked) on first use.
     */
    public function setSecretKey(string $secretKey): void
    {
        $this->secretKey = $secretKey;
    }

    /**
     * Encrypt a string using AES-256-GCM.
     *
     * Format of returned value:
     *   base64_encode( IV . TAG . CIPHERTEXT ) . '<ENC>'
     *
     * - IV: 12 random bytes (nonce)
     * - TAG: 16-byte authentication tag generated by OpenSSL
     * - CIPHERTEXT: encrypted data
     *
     * @param string|null $data Plaintext to encrypt
     * @return string|null Ciphertext with IV+tag embedded, or null if input is null
     * @throws EncryptException If encryption fails
     */
    public function encrypt(?string $data): ?string
    {
        // Return null for null input
        if (is_null($data)) {
            return null;
        }

        // If already encrypted (has <ENC> suffix), return as-is
        if (DoctrineEncryptListenerInterface::ENCRYPTED_SUFFIX === substr($data, -5)) {
            return $data;
        }

        $key = $this->getValidatedSecretKey();

        // Generate a cryptographically secure random IV (nonce)
        $iv = random_bytes(self::IV_LENGTH);

        // Tag will be filled by openssl_encrypt (passed by reference)
        $tag = '';

        $ciphertext = openssl_encrypt(
            $data,
            self::METHOD,
            $key,
            OPENSSL_RAW_DATA,
            $iv,
            $tag,
            '',            // Additional Authenticated Data (AAD) - optional
            self::TAG_LENGTH
        );

        if ($ciphertext === false) {
            $error = openssl_error_string() ?: 'Unknown OpenSSL error';
            throw new EncryptException('Encryption failed: ' . $error, $data);
        }

        // Concatenate IV + TAG + CIPHERTEXT
        $combined = $iv . $tag . $ciphertext;

        // Base64 encode for safe storage, append <ENC> suffix
        return base64_encode($combined) . DoctrineEncryptListenerInterface::ENCRYPTED_SUFFIX;
    }

    /**
     * Decrypt a string encrypted with AES-256-GCM.
     *
     * Automatically extracts IV and TAG from the ciphertext.
     * If authentication fails (tag mismatch), throws EncryptException.
     *
     * @param string|null $data Encrypted data with '<ENC>' suffix
     * @return string|null Decrypted plaintext, or null if input is null
     * @throws EncryptException If decryption fails or authentication tag is invalid
     */
    public function decrypt(?string $data): ?string
    {
        // Return null for null input
        if (is_null($data)) {
            return null;
        }

        // If no <ENC> suffix, assume already decrypted (or not for us)
        if (DoctrineEncryptListenerInterface::ENCRYPTED_SUFFIX !== substr($data, -5)) {
            return $data;
        }

        // Remove the <ENC> suffix
        $data = substr($data, 0, -5);

        // Empty string after removing suffix? Return empty string
        if (empty($data)) {
            return $data;
        }

        $key = $this->getValidatedSecretKey();

        // Base64 decode
        $decoded = base64_decode($data);
        if ($decoded === false) {
            throw new EncryptException('Invalid base64 encoded encrypted data');
        }

        // Verify minimum length: IV + TAG at minimum
        $minLength = self::IV_LENGTH + self::TAG_LENGTH;
        if (strlen($decoded) < $minLength) {
            throw new EncryptException('Encrypted data is too short to contain IV and authentication tag');
        }

        // Extract IV, TAG, and ciphertext
        $iv = substr($decoded, 0, self::IV_LENGTH);
        $tag = substr($decoded, self::IV_LENGTH, self::TAG_LENGTH);
        $ciphertext = substr($decoded, self::IV_LENGTH + self::TAG_LENGTH);

        // Decrypt and verify authentication tag
        $plaintext = openssl_decrypt(
            $ciphertext,
            self::METHOD,
            $key,
            OPENSSL_RAW_DATA,
            $iv,
            $tag
        );

        if ($plaintext === false) {
            $error = openssl_error_string() ?: 'Unknown OpenSSL error';

            // Heuristic detection of old CBC format:
            // GCM minimum length = IV(12) + TAG(16) = 28 bytes
            // If decoded data is shorter than 28 bytes, it's definitely not GCM
            // and likely the old CBC format (which used 16-byte IV, no tag)
            $decodedLength = strlen($decoded);
            $gcmMinLength = self::IV_LENGTH + self::TAG_LENGTH;

            if ($decodedLength < $gcmMinLength) {
                // Data too short to be valid GCM → likely old CBC format
                $message = sprintf(
                    'Decryption failed: data appears to be encrypted with the old CBC format (pre-v2.1). ' .
                    'Length %d bytes is less than GCM minimum of %d bytes. ' .
                    'Migrate your database first: run "php bin/console encrypt:database decrypt" with the old version, ' .
                    'then upgrade and re-encrypt with "php bin/console encrypt:database encrypt".',
                    $decodedLength,
                    $gcmMinLength
                );
                throw new EncryptException($message);
            }

            // For data of valid GCM length, we keep a generic message to avoid oracle attacks
            throw new EncryptException(
                'Decryption failed: data may be corrupted, tampered, or the encryption key is incorrect. ' .
                'If you are upgrading from a previous version, ensure you have migrated existing data first.'
            );
        }

        return $plaintext;
    }

    /**
     * Get and validate the secret key.
     *
     * Steps:
     * 1. Dispatch LOAD_KEY event to allow runtime key override
     * 2. Validate key is set
     * 3. base64_decode the key
     * 4. Verify it's exactly 32 bytes (256 bits)
     *
     * @return string Binary secret key (32 bytes)
     * @throws EncryptException If key is missing or invalid length
     */
    private function getValidatedSecretKey(): string
    {
        // Allow runtime override via event listeners
        $getKeyEvent = new EncryptKeyEvent();
        $this->dispatcher->dispatch($getKeyEvent, EncryptKeyEvents::LOAD_KEY);

        if (null !== $getKeyEvent->getKey()) {
            $this->secretKey = $getKeyEvent->getKey();
        }

        // Check that key is set
        if (empty($this->secretKey)) {
            throw new EncryptException(
                'The bundle psolutions\encrypt-bundle requires an encryption key. ' .
                'Set PSOLUTIONS_ENCRYPT_KEY in your .env file, or use the ' .
                'EncryptKeyEvents::LOAD_KEY event to provide a dynamic key. ' .
                'You can generate a key with: bin/console encrypt:genkey'
            );
        }

        // Decode from base64 (the key should be base64-encoded)
        $key = base64_decode($this->secretKey, true);
        if ($key === false) {
            throw new EncryptException('Invalid base64 encoding in encryption key');
        }

        // Verify exact length: 32 bytes = 256 bits
        $keyLength = strlen($key);
        if (32 !== $keyLength) {
            throw new EncryptException(
                sprintf(
                    'Encryption key must be 256 bits (32 bytes), got %d bits (%d bytes). ' .
                    'Generate a proper key with: bin/console encrypt:genkey',
                    $keyLength * 8,
                    $keyLength
                )
            );
        }

        return $key;
    }
}
